language: node_js
node_js:
- '0.10'
git:
  depth: 10
before_install:
- export DISPLAY=:99.0
- sh -e /etc/init.d/xvfb start
- npm install -qg bower gulp-cli
- npm install -q
- bower install --force
- bower install --force
script: gulp
deploy:
  provider: npm
  email: adrien.crivelli@gmail.com
  api_key:
    secure: QF64CeyM867euofZPYaLedYw/0v1k/RHCcZ/yNgMa0GTOAqUabXg24ho2Mbv1ABvvozn6ALPnmI8JgW6c9OaD7y6ttTHwF5nfO28GNXo3p+Gp7QC12u0wk02ypQxSaPbl/q+7tCZi5DYGuxrTzb3za/agwI5w9o/id/K8aOYlZIDETwG0sP4YNZJUBeGjCpwOBecuqmVv7Pn6LHOdawpoUarnxNMmf/yp/Ry9FZb8uBIP1DrjV4qapdac4ZvL7w0kh1fM6o3QkPW2TpX7uS+1VI5jqkpqRwLbrytf6xkRQ+9desNrn2jmsl31UFSUWr42/OSO/O+da/X5FnWSDYoU6UubcvjSH9J8wPvq9+XxRm9jdjczOZnV+y6HXjaSKHmQAYx9U6NzDefH1AoraNHG2LhJvXjFL3Grm6GFNfggCmH3YNgeCMKzHQwtv3MA57qbdRNIfCeJ2FJ0Fd1qNy+eGikpGhTEAJgv+WkQI9cSLwfXuq5dIPQ/C4xnWob54gSVV00QI7QF55XVnGvS1SjiTScN0lfMi+BKGdgQSzoF9obcC+OigG5JDAuWy4qzXxxdhZu0iaWVcdojL/OLrPzHSPVS6gm5ICdLdhSY5ersgQY0rhPBKo2T6RAlFSljPb+QYrTa+QS69EH6c8/yqcuOmMq3Vf1PAIJJmcuEvakYL8=
  on:
    tags: true
    repo: angular-ui/ui-uploader
